baseURL = "https://devopsbrain.ru"
languageCode = "en-us"
title = "DevOps Brain üß†"
theme="archie"
copyright = "¬© It Cat"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
	mode="toggle"
	useCDN=false
	subtitle = "–ü—Ä–æ—Å—Ç–æ –æ —Å–ª–æ–∂–Ω–æ–º - –∞–≤—Ç–æ—Ä—Å–∫–∏–µ –ø–æ—Å—Ç—ã —Å –±–æ–ª—å—à–∏–º –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ–º –ø—Ä–∞–∫—Ç–∏–∫–∏ –ø–æ DevOPS –∏ SRE..."
	favicon = "/favicon.ico"
	customCSS = ["css/projects.css", "css/search.css", "css/feed.css", "css/social-icons.css"]
	customJS = [
		"<script type=\"text/javascript\">(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};m[i].l=1*new Date();for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})(window, document,'script','https://mc.yandex.ru/metrika/tag.js?id=105851409', 'ym');ym(105851409, 'init', {ssr:true, webvisor:true, clickmap:true, ecommerce:\"dataLayer\", accurateTrackBounce:true, trackLinks:true});</script><noscript><div><img src=\"https://mc.yandex.ru/watch/105851409\" style=\"position:absolute; left:-9999px;\" alt=\"\" /></div></noscript>"
	]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/itcaat"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/itcaat"

[[params.social]]
name = "Telegram"
icon = "telegram"
url = "https://t.me/devopsbrain"

[[menu.main]]
name = "–ë–ª–æ–≥"
url = "/"
weight = 2

[[menu.main]]
name = "–ö–∞—Ç–µ–≥–æ—Ä–∏–∏"
url = "/tags"
weight = 3

[[menu.main]]
name = "–ü—Ä–æ–µ–∫—Ç—ã"
url = "/projects"
weight = 4

[[menu.main]]
name = "–û–±–æ –º–Ω–µ"
url = "/cv"
weight = 5


